// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Turis_Travel2.Data;

#nullable disable

namespace Turis_Travel2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251222011512_Imgpaquetes")]
    partial class Imgpaquetes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PaqueteServicio", b =>
                {
                    b.Property<int>("IdPaquete")
                        .HasColumnType("int")
                        .HasColumnName("ID_paquete");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int")
                        .HasColumnName("ID_servicio");

                    b.HasKey("IdPaquete", "IdServicio")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "IdServicio" }, "ID_servicio");

                    b.ToTable("Paquete_Servicio", (string)null);
                });

            modelBuilder.Entity("Turis_Travel2.Models.AsignacionConductore", b =>
                {
                    b.Property<int>("IdAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_asignacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAsignacion"));

                    b.Property<DateOnly?>("FechaAsignacion")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_asignacion");

                    b.Property<int?>("IdConductor")
                        .HasColumnType("int")
                        .HasColumnName("ID_conductor");

                    b.Property<int?>("IdTransporte")
                        .HasColumnType("int")
                        .HasColumnName("ID_transporte");

                    b.HasKey("IdAsignacion")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdConductor" }, "ID_conductor");

                    b.HasIndex(new[] { "IdTransporte" }, "ID_transporte");

                    b.ToTable("Asignacion_Conductores", (string)null);
                });

            modelBuilder.Entity("Turis_Travel2.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_cliente");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Cedula")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValueSql("'activo'");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_registro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdCliente")
                        .HasName("PRIMARY");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Conductore", b =>
                {
                    b.Property<int>("IdConductor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_conductor");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdConductor"));

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValueSql("'activo'");

                    b.Property<string>("Licencia")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdConductor")
                        .HasName("PRIMARY");

                    b.ToTable("Conductores");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Contrato", b =>
                {
                    b.Property<int>("IdContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_contrato");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdContrato"));

                    b.Property<string>("Condiciones")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValueSql("'activo'");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_inicio");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("ID_proveedor");

                    b.HasKey("IdContrato")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdProveedor" }, "ID_proveedor");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Destino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<sbyte?>("Estado")
                        .HasColumnType("tinyint");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pais")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Destinos");
                });

            modelBuilder.Entity("Turis_Travel2.Models.EfmigrationsHistory", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("MigrationId")
                        .HasName("PRIMARY");

                    b.ToTable("__EFMigrationsHistory", (string)null);
                });

            modelBuilder.Entity("Turis_Travel2.Models.Itinerario", b =>
                {
                    b.Property<int>("IdItinerario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_itinerario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdItinerario"));

                    b.Property<string>("Actividades")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int?>("DuracionDias")
                        .HasColumnType("int")
                        .HasColumnName("Duracion_dias");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValueSql("'borrador'");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_fin");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_inicio");

                    b.Property<int?>("IdPaquete")
                        .HasColumnType("int")
                        .HasColumnName("ID_paquete");

                    b.Property<string>("NombreItinerario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nombre_itinerario");

                    b.Property<decimal?>("PrecioPorPersona")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Precio_por_persona");

                    b.Property<string>("TipoItinerario")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Tipo_itinerario");

                    b.HasKey("IdItinerario")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdPaquete" }, "ID_paquete");

                    b.HasIndex(new[] { "NombreItinerario" }, "idx_itinerario_nombre");

                    b.ToTable("Itinerarios");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Modulo", b =>
                {
                    b.Property<int>("IdModulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_modulo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdModulo"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("NombreModulo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Nombre_modulo");

                    b.HasKey("IdModulo")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NombreModulo" }, "Nombre_modulo")
                        .IsUnique();

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Notificacione", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_notificacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<string>("Destinatario")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValueSql("'enviada'");

                    b.Property<DateTime?>("FechaEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_envio")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("IdReserva")
                        .HasColumnType("int")
                        .HasColumnName("ID_reserva");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdNotificacion")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdReserva" }, "ID_reserva");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Turis_Travel2.Models.PaquetesTuristico", b =>
                {
                    b.Property<int>("IdPaquete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_paquete");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPaquete"));

                    b.Property<int?>("CapacidadMaxima")
                        .HasColumnType("int")
                        .HasColumnName("Capacidad_maxima");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValueSql("'borrador'");

                    b.Property<DateTime?>("FechaActualizacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_actualizacion");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaActualizacion"));

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_fin");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_inicio");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("NombrePaquete")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nombre_paquete");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Precio_base");

                    b.HasKey("IdPaquete")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NombrePaquete" }, "idx_paquete_nombre")
                        .IsUnique();

                    b.ToTable("Paquetes_Turisticos", (string)null);
                });

            modelBuilder.Entity("Turis_Travel2.Models.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_permiso");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<int?>("EstadoPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Estado_permiso")
                        .HasDefaultValueSql("'1'");

                    b.Property<int>("IdModulo")
                        .HasColumnType("int")
                        .HasColumnName("ID_modulo");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("ID_rol");

                    b.HasKey("IdPermiso")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdModulo" }, "ID_modulo");

                    b.HasIndex(new[] { "IdRol" }, "ID_rol");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Proveedore", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_proveedor");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<string>("Contacto")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValueSql("'activo'");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdProveedor")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Nombre" }, "idx_proveedor_nombre");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Turis_Travel2.Models.RecuperacionContrasena", b =>
                {
                    b.Property<int>("IdRecuperacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_recuperacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRecuperacion"));

                    b.Property<DateOnly>("Expiracion")
                        .HasColumnType("date");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_usuario");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("Usado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("IdRecuperacion")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdUsuario" }, "ID_usuario");

                    b.HasIndex(new[] { "Token" }, "Token")
                        .IsUnique();

                    b.ToTable("Recuperacion_Contrasena", (string)null);
                });

            modelBuilder.Entity("Turis_Travel2.Models.Reporte", b =>
                {
                    b.Property<int>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_reporte");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdReporte"));

                    b.Property<string>("Datos")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaGeneracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_generacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdReporte")
                        .HasName("PRIMARY");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_reserva");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValueSql("'pendiente'");

                    b.Property<DateTime?>("FechaSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_solicitud")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("ID_cliente");

                    b.Property<int?>("IdItinerario")
                        .HasColumnType("int")
                        .HasColumnName("ID_itinerario");

                    b.Property<int?>("IdPaquete")
                        .HasColumnType("int")
                        .HasColumnName("ID_paquete");

                    b.Property<int?>("IdTransporte")
                        .HasColumnType("int")
                        .HasColumnName("ID_transporte");

                    b.Property<int?>("NumeroPasajeros")
                        .HasColumnType("int")
                        .HasColumnName("Numero_pasajeros");

                    b.Property<decimal?>("PrecioTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Precio_total");

                    b.HasKey("IdReserva")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdItinerario" }, "ID_itinerario");

                    b.HasIndex(new[] { "IdPaquete" }, "ID_paquete")
                        .HasDatabaseName("ID_paquete1");

                    b.HasIndex(new[] { "IdTransporte" }, "ID_transporte")
                        .HasDatabaseName("ID_transporte1");

                    b.HasIndex(new[] { "IdCliente" }, "idx_reserva_usuario");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Retroalimentacion", b =>
                {
                    b.Property<int>("IdRetroalimentacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_retroalimentacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRetroalimentacion"));

                    b.Property<int?>("Anonimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int")
                        .HasColumnName("ID_reserva");

                    b.Property<int?>("Puntuacion")
                        .HasColumnType("int");

                    b.HasKey("IdRetroalimentacion")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdReserva" }, "ID_reserva")
                        .HasDatabaseName("ID_reserva1");

                    b.ToTable("Retroalimentacion", (string)null);
                });

            modelBuilder.Entity("Turis_Travel2.Models.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_rol");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<int?>("EstadoRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Estado_rol")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Nombre_rol");

                    b.HasKey("IdRol")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NombreRol" }, "Nombre_rol")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Servicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_servicio");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdServicio"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValueSql("'activo'");

                    b.Property<string>("NombreServicio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nombre_servicio");

                    b.HasKey("IdServicio")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NombreServicio" }, "Nombre_servicio")
                        .IsUnique();

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Transporte", b =>
                {
                    b.Property<int>("IdTransporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_transporte");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTransporte"));

                    b.Property<int?>("Capacidad")
                        .HasColumnType("int");

                    b.Property<int?>("Disponibilidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValueSql("'activo'");

                    b.Property<int?>("IdPaquete")
                        .HasColumnType("int")
                        .HasColumnName("ID_paquete");

                    b.Property<string>("TipoVehiculo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Tipo_vehiculo");

                    b.HasKey("IdTransporte")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdPaquete" }, "ID_paquete")
                        .HasDatabaseName("ID_paquete2");

                    b.ToTable("Transportes");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'1'");

                    b.Property<DateTime?>("FechaActualizacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_actualizacion");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaActualizacion"));

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("ID_rol");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nombre_usuario");

                    b.Property<string>("Observacion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdUsuario")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Correo" }, "Correo")
                        .IsUnique();

                    b.HasIndex(new[] { "IdRol" }, "ID_rol")
                        .HasDatabaseName("ID_rol1");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PaqueteServicio", b =>
                {
                    b.HasOne("Turis_Travel2.Models.PaquetesTuristico", null)
                        .WithMany()
                        .HasForeignKey("IdPaquete")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Paquete_Servicio_ibfk_1");

                    b.HasOne("Turis_Travel2.Models.Servicio", null)
                        .WithMany()
                        .HasForeignKey("IdServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Paquete_Servicio_ibfk_2");
                });

            modelBuilder.Entity("Turis_Travel2.Models.AsignacionConductore", b =>
                {
                    b.HasOne("Turis_Travel2.Models.Conductore", "IdConductorNavigation")
                        .WithMany("AsignacionConductores")
                        .HasForeignKey("IdConductor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("Asignacion_Conductores_ibfk_1");

                    b.HasOne("Turis_Travel2.Models.Transporte", "IdTransporteNavigation")
                        .WithMany("AsignacionConductores")
                        .HasForeignKey("IdTransporte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("Asignacion_Conductores_ibfk_2");

                    b.Navigation("IdConductorNavigation");

                    b.Navigation("IdTransporteNavigation");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Contrato", b =>
                {
                    b.HasOne("Turis_Travel2.Models.Proveedore", "IdProveedorNavigation")
                        .WithMany("Contratos")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Contratos_ibfk_1");

                    b.Navigation("IdProveedorNavigation");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Itinerario", b =>
                {
                    b.HasOne("Turis_Travel2.Models.PaquetesTuristico", "IdPaqueteNavigation")
                        .WithMany("Itinerarios")
                        .HasForeignKey("IdPaquete")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("Itinerarios_ibfk_1");

                    b.Navigation("IdPaqueteNavigation");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Notificacione", b =>
                {
                    b.HasOne("Turis_Travel2.Models.Reserva", "IdReservaNavigation")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Notificaciones_ibfk_1");

                    b.Navigation("IdReservaNavigation");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Permiso", b =>
                {
                    b.HasOne("Turis_Travel2.Models.Modulo", "IdModuloNavigation")
                        .WithMany("Permisos")
                        .HasForeignKey("IdModulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Permisos_ibfk_2");

                    b.HasOne("Turis_Travel2.Models.Role", "IdRolNavigation")
                        .WithMany("Permisos")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Permisos_ibfk_1");

                    b.Navigation("IdModuloNavigation");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("Turis_Travel2.Models.RecuperacionContrasena", b =>
                {
                    b.HasOne("Turis_Travel2.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("RecuperacionContrasenas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Recuperacion_Contrasena_ibfk_1");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Reserva", b =>
                {
                    b.HasOne("Turis_Travel2.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservas_cliente");

                    b.HasOne("Turis_Travel2.Models.Itinerario", "IdItinerarioNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdItinerario")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Reservas_ibfk_3");

                    b.HasOne("Turis_Travel2.Models.PaquetesTuristico", "IdPaqueteNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdPaquete")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Reservas_ibfk_2");

                    b.HasOne("Turis_Travel2.Models.Transporte", "IdTransporteNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdTransporte")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Reservas_ibfk_4");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdItinerarioNavigation");

                    b.Navigation("IdPaqueteNavigation");

                    b.Navigation("IdTransporteNavigation");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Retroalimentacion", b =>
                {
                    b.HasOne("Turis_Travel2.Models.Reserva", "IdReservaNavigation")
                        .WithMany("Retroalimentacions")
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Retroalimentacion_ibfk_1");

                    b.Navigation("IdReservaNavigation");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Transporte", b =>
                {
                    b.HasOne("Turis_Travel2.Models.PaquetesTuristico", "IdPaqueteNavigation")
                        .WithMany("Transportes")
                        .HasForeignKey("IdPaquete")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Transportes_ibfk_1");

                    b.Navigation("IdPaqueteNavigation");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Usuario", b =>
                {
                    b.HasOne("Turis_Travel2.Models.Role", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Usuarios_ibfk_1");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Conductore", b =>
                {
                    b.Navigation("AsignacionConductores");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Itinerario", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Modulo", b =>
                {
                    b.Navigation("Permisos");
                });

            modelBuilder.Entity("Turis_Travel2.Models.PaquetesTuristico", b =>
                {
                    b.Navigation("Itinerarios");

                    b.Navigation("Reservas");

                    b.Navigation("Transportes");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Proveedore", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Reserva", b =>
                {
                    b.Navigation("Notificaciones");

                    b.Navigation("Retroalimentacions");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Role", b =>
                {
                    b.Navigation("Permisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Transporte", b =>
                {
                    b.Navigation("AsignacionConductores");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Turis_Travel2.Models.Usuario", b =>
                {
                    b.Navigation("RecuperacionContrasenas");
                });
#pragma warning restore 612, 618
        }
    }
}
